[workspace]
members = ["bridge-proto", "gateway", "client", "bridge-client-core"]
resolver = "2"

[package]
name = "opcda-bridge"
version = "0.1.5"
edition = "2024"
description = "OPC DA gateway/client bridge between Windows and Linux"
license = "MIT"
repository = "https://github.com/mikeboiko/opcda-bridge"

[dependencies]
thiserror = "2"
