name: Release

on:
  push:
    tags:
      - 'opcda-bridge-gateway-v*'
      - 'opcda-bridge-client-v*'

jobs:
  release-gateway:
    if: startsWith(github.ref_name, 'opcda-bridge-gateway-v')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      - uses: taiki-e/install-action@v2
        with:
          tool: protoc

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: opcda-bridge-gateway
          manifest_path: gateway/Cargo.toml
          target: i686-pc-windows-msvc
          token: ${{ secrets.GITHUB_TOKEN }}

  release-client:
    if: startsWith(github.ref_name, 'opcda-bridge-client-v')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      max-parallel: 1
    steps:
      - uses: actions/checkout@v5

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: opcda-bridge-client
          manifest_path: client/Cargo.toml
          token: ${{ secrets.GITHUB_TOKEN }}
